FROM toolhippie/manifest-tool:2.1.8
RUN wget https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.9.0/linux-amd64/docker-credential-ecr-login && \
    mv docker-credential-ecr-login /usr/local/bin && \
    mkdir -p $HOME/.docker && \
    echo "{\"credsStore\": \"ecr-login\"}"
