apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-kaniko-arm64
  namespace: jenkins
  labels:
    app: jenkins-agent-kaniko
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2
    imagePullPolicy: Always
    command:
      - sleep
    args:
      - 99d
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      emptyDir: {}
