apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent-kaniko
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      emptyDir: {}
