apiVersion: v1
kind: Pod
metadata:
  name: kaniko-arm64
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
    - name: kaniko
      env:
      - name: AWS_SDK_LOAD_CONFIG
        value: "true"
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: docker-config
    emptyDir: {}