apiVersion: v1
kind: Pod
metadata:
  name: manifest-tool
  namespace: jenkins
  labels:
    app: jenkins-agent-manifest-tool
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: manifest-tool
    image: mplatform/manifest-tool
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker
  volumes:
  - name: docker-config
    emptyDir: {}
