apiVersion: v1
kind: Pod
metadata:
  name: manifest-tool
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: manifest-tool
      image: 600413481647.dkr.ecr.us-west-2.amazonaws.com/manifest-tool:2.1.8-ecr
      command:
        - sleep
      args:
        - 99d
  restartPolicy: Never
