apiVersion: v1
kind: Pod
metadata:
  name: manifest-tool
  namespace: jenkins
  labels:
    app: jenkins-agent-manifest-tool
spec:
  serviceAccountName: jenkins
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: manifest-tool
    image: mplatform/manifest-tool:v2.1.8
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker
  - name: awscli
    image: public.ecr.aws/aws-cli/aws-cli:2.22.4
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker
  volumes:
  - name: docker-config
    emptyDir: {}
