apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023
spec:
  amiSelectorTerms:
  - alias: al2023@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      iops: 3000
      throughput: 125
      volumeSize: 50Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: KarpenterNodeRole-dev-cluster
  securityGroupSelectorTerms:
  - tags:
      kubernetes.io/cluster/dev-cluster: owned
  subnetSelectorTerms:
  - tags:
      eksctl.cluster.k8s.io/v1alpha1/cluster-name: dev-cluster
      kubernetes.io/role/internal-elb: "1"